name = "freemarketingstore"
compatibility_date = "2026-03-17"
pages_build_output_dir = ".deploy"

[[d1_databases]]
binding = "FMS_DB"
database_name = "fms-production"
database_id = "01df111b-5072-4195-abd0-4661d4dd47ae"
